server:
  port: ${envpt.tomcatPortPre}0131

#jwt相关
jwt-properties:
  secret: ruixiude@Login(Auth}*^31)&kuanghua% # 登录校验的密钥（盐）
  expire: 4320 # 过期时间,单位分钟
  cookieName:  KH_TOKEN
  cookieMaxAge: 1800

